# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import weather_pb2 as weather__pb2


class WeatherServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Get = channel.unary_unary(
        '/weather.WeatherService/Get',
        request_serializer=weather__pb2.WeatherRequest.SerializeToString,
        response_deserializer=weather__pb2.WeatherResponse.FromString,
        )


class WeatherServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Get(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WeatherServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Get': grpc.unary_unary_rpc_method_handler(
          servicer.Get,
          request_deserializer=weather__pb2.WeatherRequest.FromString,
          response_serializer=weather__pb2.WeatherResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'weather.WeatherService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
