# use image
FROM python_weather_base_image

# copy my code to the container
ADD . /opt/weather_service
WORKDIR /opt/weather_service

# expose port
EXPOSE 5000

# start app
CMD [ "python", "webserver/webserver.py" ]
